sprint9_v1
mikhail-kirov/java-filmorate pull request #5
Opened 2024-02-03 23:36 UTC by mikhail-kirov

2024-02-04 10:12 UTC, mikhail-kirov commented
Создана модель данных, добавлены контроллеры, валидация и логирование. Валидация через spring-boot-starter-validation покрывает часть кода, написанной вручную. Нужно этот ручной код убирать?

2024-02-05 07:20 UTC, mikita95 requested changes
Все сделано отлично. Оставил лишь несколько замечаний

2024-02-05 07:20 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final Map<Integer, Film> films = new HashMap<>();
Лучше было бы вынести логику хранения данных в отдельный класс - так ответственности будут разграничены

2024-02-05 07:20 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    final Map<Integer, User> users = new HashMap<>();
Не хватает модификатора доступа

2024-02-05 07:20 UTC, mikita95 commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +    void valUserEmptyRequestTest() {
Закомментированного кода быть не должно

2024-02-07 02:07 UTC, mikita95 approved these changes
Все отлично. Можно мержить пул-реквест

2024-02-07 19:50 UTC, merged